version: "3"
services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/data//conf:/etc/letsencrypt
      - ./certbot/data/www:/var/www/certbot
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    image: nginx:alpine
    depends_on:
      - portfolio
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/data//conf:/etc/letsencrypt
      - ./certbot/data/www:/var/www/certbot
    # command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  portfolio:
    build: ./portfolio
    restart: always
    depends_on:
      - mysql
    env_file:
      - ./.env
    volumes:
      - ./portfolio/data:/var/lib/ghost/content
