version: "3"
services:
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./certbot/html:/usr/share/nginx/html
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
    # command: "--version"
    command: "certonly --non-interactive --webroot --webroot-path=/usr/share/nginx/html -m hq@kantacky.com --agree-tos -d www.kantacky.com -d www.chatlab.space -d www.nanosuke.kantacky.com"
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  chatlab:
    image: ghost:alpine
    restart: always
    env_file:
      - ./.chatlab.env
    volumes:
      - ./chatlab/data:/var/lib/ghost/content

  nanosuke:
    image: ghost:alpine
    restart: always
    env_file:
      - ./.nanosuke.env
    volumes:
      - ./nanosuke/data:/var/lib/ghost/content

  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - chatlab
      - nanosuke
      - portfolio
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./nginx/conf.https:/etc/nginx/conf.d
      - ./nginx/conf.http:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/html:/usr/share/nginx/html
      - ./certbot/letsencrypt:/etc/letsencrypt
    command: '/bin/sh -c ''while :; do sleep 36h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  portfolio:
    image: ghost:alpine
    restart: always
    env_file:
      - ./.portfolio.env
    volumes:
      - ./portfolio/data:/var/lib/ghost/content
