FROM ghost:alpine

ENV database__client mysql
ENV database__connection__host ${MYSQL_HOST}
ENV database__connection__port ${MYSQL_PORT}
ENV database__connection__user ${MYSQL_USER}
ENV database__connection__password ${MYSQL_PASSWORD}
ENV database__connection__database ${MYSQL_DATABASE}
ENV url https://www.kantacky.com
